
###
// Register
POST http://localhost:3200/auth/register/v2/
content-type: application/json

{
    "email": "lswme@gmail.com",
    "password": "1233dfs4",
    "nameFirst": "first name",
    "nameLast": "last name"
}


###
// Channel Create
POST http://localhost:3200/channels/create/v2
content-type: application/json

{   
    "token": "1QH7ePTacc",
    "name": "Channel 1",
    "isPublic": "true"
}


###
// Login
POST http://localhost:3200/auth/login/v2/
content-type: application/json

{
    "email": "lawme@gmail.com",
    "password": "123dfs4"
}


###
//Clear
DELETE http://localhost:3200/clear/v1/
content-type: application/json


###
//debug - print all dataStore
POST http://localhost:3200/debug/
content-type: application/json
