
###
// Register
POST http://localhost:3500/auth/register/v2/
content-type: application/json

{
    "email": "b@gmail.com",
    "password": "123456",
    "nameFirst": "First Name 0",
    "nameLast": "Last Name 0"
}
###
// Login
POST http://localhost:3500/auth/login/v2/
content-type: application/json

{
    "email": "b@gmail.com",
    "password": "123456"
}
###
// Logout
POST http://localhost:3500/auth/logout/v1/
content-type: application/json

{   
    "token": "A11TW/IUXu"
}
###
// Channel Create
POST http://localhost:3500/channels/create/v2
content-type: application/json

{   
    "token": "token",
    "name": "Channel 2",
    "isPublic": "true"
}
###
// Dm Create
POST http://localhost:3500/dm/create/v1
content-type: application/json

{   
    "token": "kJ2RT5EALB",
    "uIds": []
}

###
// Dm send message
POST http://localhost:3500/message/senddm/v1
content-type: application/json

{   
    "token": "rgbprd/1Hq",
    "dmId": 3419783552,
    "message": "Here is a message"
}

###
// Get DM messages
GET http://localhost:3500/dm/messages/v1
    ?token=token0
    &start=0
    &dmId=0
     
###
// DM Details
GET http://localhost:3500/dm/details/v1
    ?token=luyMtdUMbT
    &dmId=4158043789
     
###
// dm list
GET http://localhost:3500/dm/list/v1
    ?token=kJ2RT5EALB
    
###
// DM remove 
DELETE http://localhost:3500/dm/remove/v1
    ?token=kJ2RT5EALB
    &dmId=4158043789




###
// Message send
POST http://localhost:3500/message/send/v1/
content-type: application/json

{   
    "token": "token",
    "channelId": 0,
    "message": "message 1"
}
###
// remove message
DELETE http://localhost:3500/message/remove/v1
    ?token=token
    &messageId=0

### Edit message
PUT http://localhost:3500/message/edit/v1
content-type: application/json

{   
    "token": "token",
    "messageId": 0,
    "message": ""
}

###
// User profile
GET http://localhost:3500/user/profile/v2
    ?uId=0
    &token=DP3CQxjO7r
    
###
// User All
GET http://localhost:3500/users/all/v1
    ?token=token1
    
###
// channel list all
GET http://localhost:3500/channels/listAll/v2
    ?token=token1
    

###
// Get messages
GET http://localhost:3500/channel/messages/v2
    ?token=O28xpMia3D
    &start=57
    &channelId=0
     


### Setname User
PUT http://localhost:3500/user/profile/setname/v1
content-type: application/json

{   
    "token": "hvdB6R0fpD",
    "nameFirst": "xx",
    "nameLast": "yy"
}


###
// Channel Join
POST http://localhost:3500/channel/join/v2
content-type: application/json

{   
    "token": "5kulR7Mzar",
    "channelId": 0
}
###
// Remove owner
POST http://localhost:3500/channel/removeowner/v1
content-type: application/json

{   
    "token": "token",
    "channelId": 0,
    "uId": 0
}








###
//Clear
DELETE http://localhost:3500/clear/v1/
content-type: application/json

